/**
 * Per-category brand index — the comprehensive list of brands we source
 * for each room. Sourced from the BRANDS 151 doc + Counter Cultures
 * artisanal partners. Used by the category-page Brand Wall.
 *
 * Brand pages exist for some names (matched in BRANDS via slug). For the
 * rest we render the name only — no link — until the brand page lands.
 *
 * Flagship brands render larger to set hierarchy. Editorial weight, not
 * commercial.
 */
import type { BilingualText } from "./types";

export interface CategoryBrand {
  /** Brand display name */
  name: string;
  /** Internal brand slug — present if we have a brand page; component
   *  decides whether to render as link or static name. */
  slug?: string;
  /** Larger weight in the typographic wall. Reserved for the names that
   *  define the category. */
  flagship?: boolean;
}

export interface CategoryBrandSection {
  id: string;
  label: BilingualText;
  brands: CategoryBrand[];
}

/* ──────────────────────────────────────────────────────────────────────
   BATHROOM
   ────────────────────────────────────────────────────────────────────── */

export const BATHROOM_BRAND_INDEX: CategoryBrandSection[] = [
  {
    id: "faucetry",
    label: { en: "Faucetry & Showers", es: "Grifería y Regaderas" },
    brands: [
      { name: "Kohler", slug: "kohler", flagship: true },
      { name: "Brizo", slug: "brizo", flagship: true },
      { name: "Hansgrohe", flagship: true },
      { name: "Dornbracht", flagship: true },
      { name: "Axor", flagship: true },
      { name: "California Faucets", slug: "california-faucets", flagship: true },
      { name: "Newport Brass" },
      { name: "Kallista" },
      { name: "Watermark" },
      { name: "Gessi" },
      { name: "Graff" },
      { name: "Perrin & Rowe" },
      { name: "Rohl" },
      { name: "Kingston Brass" },
      { name: "Riobel" },
      { name: "Symmons" },
      { name: "Grohe" },
      { name: "Moen" },
      { name: "Delta", slug: "delta" },
      { name: "Pfister" },
      { name: "DXV", slug: "dxv" },
      { name: "Jaclo" },
      { name: "Speakman" },
      { name: "American Standard" },
      { name: "Chicago Faucets", slug: "chicago-faucets" },
      { name: "Fortis" },
      { name: "Sigma" },
      { name: "Santec" },
      { name: "KWC" },
      { name: "Rubinet" },
      { name: "LaCava" },
      { name: "Alape" },
      { name: "WS Bath Collections" },
      { name: "Whitehaus" },
      { name: "ALFI Brand" },
      { name: "Anzzi" },
      { name: "Miseno" },
      { name: "Olympia Faucets" },
      { name: "Pioneer Faucets" },
      { name: "Peerless" },
      { name: "Central Brass" },
      { name: "Gerber" },
      { name: "PROFLO" },
      { name: "Zurn" },
      { name: "Sloan" },
      { name: "T&S Brass" },
      { name: "Viega" },
      { name: "Amba Products" },
      { name: "Signature Hardware" },
      { name: "Design House" },
      { name: "Altair" },
      { name: "Windom Bay" },
    ],
  },
  {
    id: "sinks",
    label: { en: "Sinks", es: "Lavabos" },
    brands: [
      { name: "TOTO", slug: "toto", flagship: true },
      { name: "Kohler", slug: "kohler", flagship: true },
      { name: "Badeloft", slug: "badeloft", flagship: true },
      { name: "Stone Forest", flagship: true },
      { name: "Native Trails", flagship: true },
      { name: "Victoria & Albert", flagship: true },
      { name: "Duravit" },
      { name: "Linkasink" },
      { name: "Thompson Traders" },
      { name: "MTI Baths" },
      { name: "Sietto" },
      { name: "Julien" },
      { name: "Cheviot" },
      { name: "Franke" },
      { name: "Alno" },
      { name: "ICERA" },
      { name: "Dornbracht" },
      { name: "DXV", slug: "dxv" },
      { name: "Kallista" },
      { name: "Rohl" },
      { name: "Whitehaus" },
      { name: "Ruvati" },
      { name: "Elkay" },
      { name: "Karran USA" },
      { name: "Houzer" },
      { name: "Mansfield" },
      { name: "American Standard" },
      { name: "Sterling", slug: "sterling" },
      { name: "Grohe" },
      { name: "Anzzi" },
      { name: "Miseno" },
      { name: "ALFI Brand" },
      { name: "Swiss Madison" },
      { name: "Nameeks" },
      { name: "Hardware Resources" },
      { name: "WS Bath Collections" },
      { name: "PROFLO" },
      { name: "Ackland" },
      { name: "A&E Bath and Shower" },
      { name: "Altair" },
      { name: "Signature Hardware" },
    ],
  },
  {
    id: "tubs",
    label: { en: "Bathtubs", es: "Bañeras" },
    brands: [
      { name: "Badeloft", slug: "badeloft", flagship: true },
      { name: "Victoria & Albert", flagship: true },
      { name: "Kallista", flagship: true },
      { name: "Kohler", slug: "kohler", flagship: true },
      { name: "BainUltra", flagship: true },
      { name: "MTI Baths", flagship: true },
      { name: "Aquaspa", slug: "aquaspa" },
      { name: "Jacuzzi" },
      { name: "Maax" },
      { name: "Hydrosystems" },
      { name: "DreamLine" },
      { name: "Native Trails" },
      { name: "Duravit" },
      { name: "TOTO", slug: "toto" },
      { name: "Axor" },
      { name: "DXV", slug: "dxv" },
      { name: "American Standard" },
      { name: "Sterling", slug: "sterling" },
      { name: "Wyndham Collection" },
      { name: "Ove Decors" },
      { name: "Avano" },
      { name: "Eago" },
      { name: "Anzzi" },
      { name: "ALFI Brand" },
      { name: "Pulse" },
      { name: "Swiss Madison" },
      { name: "Transolid" },
      { name: "Whitehaus" },
      { name: "Ruvati" },
      { name: "Miseno" },
      { name: "PROFLO" },
      { name: "A&E Bath and Shower" },
      { name: "Altair" },
      { name: "Signature Hardware" },
    ],
  },
  {
    id: "tile",
    label: { en: "Tile", es: "Azulejo" },
    brands: [
      { name: "Original Mission Tile", slug: "original-mission-tile", flagship: true },
      { name: "Marazzi", flagship: true },
      { name: "Sukabumi Stone México", flagship: true },
      { name: "Bedrosians" },
      { name: "Emser Tile" },
      { name: "Merola Tile" },
      { name: "Cruz Bay Studio" },
      { name: "Shaw" },
      { name: "Ackland" },
    ],
  },
  {
    id: "artisanal",
    label: {
      en: "Counter Cultures Artisanal",
      es: "Artesanal Counter Cultures",
    },
    brands: [
      { name: "Counter Cultures", flagship: true },
      { name: "Mistoa", flagship: true },
      { name: "Don Miguel · Santa Clara del Cobre", flagship: true },
      { name: "Taller Piedra Viva" },
      { name: "Sun Valley Bronze", slug: "sun-valley-bronze" },
    ],
  },
];

/* ──────────────────────────────────────────────────────────────────────
   KITCHEN
   ────────────────────────────────────────────────────────────────────── */

export const KITCHEN_BRAND_INDEX: CategoryBrandSection[] = [
  {
    id: "faucetry",
    label: { en: "Faucetry & Pot Fillers", es: "Grifería y Llenadores" },
    brands: [
      { name: "Brizo", slug: "brizo", flagship: true },
      { name: "Kohler", slug: "kohler", flagship: true },
      { name: "California Faucets", slug: "california-faucets", flagship: true },
      { name: "Hansgrohe", flagship: true },
      { name: "Dornbracht", flagship: true },
      { name: "Waterstone", flagship: true },
      { name: "Axor" },
      { name: "Newport Brass" },
      { name: "Watermark" },
      { name: "Gessi" },
      { name: "Graff" },
      { name: "Perrin & Rowe" },
      { name: "Rohl", slug: "rohl" },
      { name: "Kallista" },
      { name: "Kingston Brass" },
      { name: "Riobel" },
      { name: "Symmons" },
      { name: "Grohe" },
      { name: "Moen" },
      { name: "Delta", slug: "delta" },
      { name: "Pfister" },
      { name: "Kraus" },
      { name: "Whitehaus" },
      { name: "ALFI Brand" },
      { name: "KWC" },
      { name: "Rubinet" },
      { name: "Santec" },
      { name: "Sigma" },
      { name: "Fortis" },
      { name: "LaCava" },
      { name: "DXV", slug: "dxv" },
      { name: "Jaclo" },
      { name: "Anzzi" },
      { name: "Miseno" },
      { name: "Chicago Faucets", slug: "chicago-faucets" },
      { name: "Pioneer Faucets" },
      { name: "Olympia Faucets" },
      { name: "Peerless" },
      { name: "Central Brass" },
      { name: "Karran USA" },
      { name: "Ruvati" },
      { name: "Gerber" },
      { name: "PROFLO" },
      { name: "Zurn" },
      { name: "Sloan" },
      { name: "T&S Brass" },
      { name: "Viega" },
      { name: "Signature Hardware" },
      { name: "Design House" },
      { name: "Altair" },
    ],
  },
  {
    id: "sinks",
    label: { en: "Sinks", es: "Tarjas" },
    brands: [
      { name: "BLANCO", slug: "blanco", flagship: true },
      { name: "Kohler", slug: "kohler", flagship: true },
      { name: "Franke", flagship: true },
      { name: "Native Trails", flagship: true },
      { name: "Elkay", flagship: true },
      { name: "Julien" },
      { name: "Houzer" },
      { name: "Karran USA" },
      { name: "Ruvati" },
      { name: "Kraus" },
      { name: "Thompson Traders" },
      { name: "Whitehaus" },
      { name: "ALFI Brand" },
      { name: "Sterling", slug: "sterling" },
      { name: "Cheviot" },
      { name: "Mansfield" },
      { name: "Rohl", slug: "rohl" },
      { name: "Anzzi" },
      { name: "Miseno" },
    ],
  },
  {
    id: "appliances",
    label: { en: "Appliances & Hoods", es: "Electrodomésticos y Campanas" },
    brands: [
      { name: "BlueStar", slug: "bluestar", flagship: true },
      { name: "SMEG", slug: "smeg", flagship: true },
      { name: "Teka", slug: "teka", flagship: true },
      { name: "Fisher & Paykel", flagship: true },
      { name: "Banté" },
    ],
  },
  {
    id: "tile",
    label: { en: "Tile", es: "Azulejo" },
    brands: [
      { name: "Original Mission Tile", slug: "original-mission-tile", flagship: true },
      { name: "Marazzi", flagship: true },
      { name: "Bedrosians", flagship: true },
      { name: "Emser Tile" },
      { name: "Merola Tile" },
      { name: "Cruz Bay Studio" },
      { name: "Sukabumi Stone México" },
      { name: "Shaw" },
      { name: "Ackland" },
    ],
  },
  {
    id: "artisanal",
    label: {
      en: "Counter Cultures Artisanal",
      es: "Artesanal Counter Cultures",
    },
    brands: [
      { name: "Counter Cultures", flagship: true },
      { name: "Mistoa", flagship: true },
      { name: "Don Miguel · Santa Clara del Cobre", flagship: true },
      { name: "Sun Valley Bronze", slug: "sun-valley-bronze" },
    ],
  },
];

/* ──────────────────────────────────────────────────────────────────────
   DOOR & CABINET HARDWARE
   ────────────────────────────────────────────────────────────────────── */

export const HARDWARE_BRAND_INDEX: CategoryBrandSection[] = [
  {
    id: "door",
    label: { en: "Door Hardware", es: "Herrajes de Puerta" },
    brands: [
      { name: "Sun Valley Bronze", slug: "sun-valley-bronze", flagship: true },
      { name: "Emtek", slug: "emtek", flagship: true },
      { name: "Baldwin", slug: "baldwin", flagship: true },
      { name: "Rocky Mountain Hardware", flagship: true },
      { name: "Hardware Renaissance", flagship: true },
      { name: "Buster + Punch", flagship: true },
      { name: "Ashley Norton" },
      { name: "Omnia" },
      { name: "Grandeur" },
      { name: "Linnea" },
      { name: "Manzoni" },
      { name: "Nostalgic Warehouse" },
      { name: "Ageless Iron" },
      { name: "Vesta Fine Hardware" },
      { name: "Schaub and Company" },
      { name: "Colonial Bronze" },
      { name: "R. Christensen" },
      { name: "Delaney" },
      { name: "Pamex" },
      { name: "Perrin & Rowe" },
      { name: "IDH by St. Simons" },
      { name: "Acorn Manufacturing" },
      { name: "Deltana" },
      { name: "S. Parker Hardware" },
    ],
  },
  {
    id: "cabinet",
    label: { en: "Cabinet Hardware", es: "Herrajes de Gabinete" },
    brands: [
      { name: "Top Knobs", flagship: true },
      { name: "Hickory Hardware", flagship: true },
      { name: "Atlas Homewares", flagship: true },
      { name: "Amerock", flagship: true },
      { name: "Du Verre", flagship: true },
      { name: "Sietto" },
      { name: "Belwith Keeler" },
      { name: "Berenson" },
      { name: "Jeffrey Alexander" },
      { name: "Liberty Hardware" },
      { name: "Crown Cabinet Hardware" },
      { name: "Hardware Resources" },
      { name: "Richelieu" },
      { name: "KasaWare" },
      { name: "Hapny Home" },
      { name: "Häfele" },
      { name: "RK International" },
      { name: "Rusticware" },
      { name: "Elements" },
      { name: "Siro Designs" },
      { name: "Franklin Brass" },
      { name: "Keeler" },
      { name: "Alno" },
      { name: "DesignPerfect" },
      { name: "Classic Brass" },
      { name: "Sugatsune" },
      { name: "Signature Hardware" },
      { name: "Design House" },
    ],
  },
  {
    id: "artisanal",
    label: {
      en: "Counter Cultures Artisanal",
      es: "Artesanal Counter Cultures",
    },
    brands: [
      { name: "Counter Cultures", flagship: true },
      { name: "Sun Valley Bronze", slug: "sun-valley-bronze", flagship: true },
      { name: "San Miguel Forge · Hand-Forged Jaladeras", flagship: true },
    ],
  },
];

export const CATEGORY_BRAND_INDEX: Record<string, CategoryBrandSection[]> = {
  bathroom: BATHROOM_BRAND_INDEX,
  kitchen: KITCHEN_BRAND_INDEX,
  hardware: HARDWARE_BRAND_INDEX,
};
