export const SITE_CONFIG = {
  name: "Counter Cultures",
  tagline: "Premium Kitchen, Bath & Hardware",
  description:
    "San Miguel de Allende's premier kitchen, bath, and architectural hardware showroom. Authorized dealer for Kohler, TOTO, Brizo, BLANCO, and 15 more brands — plus Mexican artisan pieces. 491 curated products, sourced worldwide and delivered to your project.",
  url: "https://countercultures.com.mx",
  showroom: {
    address: "Providencia, San Miguel de Allende, Guanajuato, Mexico",
    phone: "415.154.8375",
    email: "info@countercultures.com.mx",
    whatsapp: "415.154.8375",
    hours: "Lunes a Viernes, 10:00 – 18:00",
  },
  social: {
    instagram: "https://instagram.com/countercultures",
    facebook: "https://facebook.com/countercultures",
    pinterest: "https://pinterest.com/countercultures",
  },
} as const;

export const NAV_LINKS = [
  {
    label: { en: "Shop", es: "Tienda" },
    href: "/shop",
    children: [
      { label: { en: "Bathroom", es: "Baño" }, href: "/shop/bathroom" },
      { label: { en: "Kitchen", es: "Cocina" }, href: "/shop/kitchen" },
      { label: { en: "Door Hardware", es: "Chapas y Herrajes" }, href: "/shop/hardware" },
    ],
  },
  {
    label: { en: "Brands & Makers", es: "Marcas y Artesanos" },
    href: "/brands",
  },
  {
    label: { en: "Our Story", es: "Nuestra Historia" },
    href: "/our-story",
  },
  {
    label: { en: "Insights", es: "Insights" },
    href: "/insights",
  },
  {
    label: { en: "Resources", es: "Recursos" },
    href: "/resources",
  },
] as const;

export const BRANDS = [
  { name: "Kohler", slug: "kohler" },
  { name: "TOTO", slug: "toto" },
  { name: "Brizo", slug: "brizo" },
  { name: "BLANCO", slug: "blanco" },
  { name: "California Faucets", slug: "california-faucets" },
  { name: "Sun Valley Bronze", slug: "sun-valley-bronze" },
  { name: "Emtek", slug: "emtek" },
  { name: "Badeloft", slug: "badeloft" },
  { name: "Banté", slug: "bante" },
  { name: "Mistoa", slug: "mistoa" },
  { name: "Villeroy & Boch", slug: "villeroy-boch" },
  { name: "AquaSpa", slug: "aquaspa" },
  { name: "Ebbe", slug: "ebbe" },
  { name: "Delta", slug: "delta" },
  { name: "ROHL", slug: "rohl" },
  { name: "Teka", slug: "teka" },
  { name: "SMEG", slug: "smeg" },
  { name: "Bluestar", slug: "bluestar" },
  { name: "Baldwin", slug: "baldwin" },
] as const;

export const PRODUCT_CATEGORIES = {
  bathroom: {
    label: { en: "Bathroom", es: "Baño" },
    slug: "bathroom",
    subcategories: [
      { slug: "sinks", label: { en: "Sinks & Basins", es: "Lavabos" }, originalPath: "bano/lavabos" },
      { slug: "faucets", label: { en: "Faucets", es: "Grifos" }, originalPath: "bano/grifos" },
      { slug: "bathtubs", label: { en: "Bathtubs", es: "Bañeras" }, originalPath: "bano/baneras" },
      { slug: "tub-fillers", label: { en: "Tub Fillers", es: "Llenadores de Bañera" }, originalPath: "bano/llenador-de-banera" },
      { slug: "spa", label: { en: "Spa & Hydrotherapy", es: "Spa" }, originalPath: "bano/spa" },
      { slug: "toilets", label: { en: "Toilets & WASHLET", es: "Sanitarios" }, originalPath: "bano/sanitarios" },
      { slug: "showers", label: { en: "Showers & Shower Systems", es: "Regaderas y Duchas" }, originalPath: "bano/regaderasyduchas" },
      { slug: "accessories", label: { en: "Accessories", es: "Accesorios" }, originalPath: "bano/accesorios" },
      { slug: "drains", label: { en: "Drains", es: "Drenajes" }, originalPath: "bano/drenajes" },
      { slug: "valves", label: { en: "Valves", es: "Válvulas" }, originalPath: "bano/valvulas" },
    ],
  },
  kitchen: {
    label: { en: "Kitchen", es: "Cocina" },
    slug: "kitchen",
    subcategories: [
      { slug: "sinks", label: { en: "Sinks & Basins", es: "Tarjas y Fregaderos" }, originalPath: "cocina/tarjas-y-fregaderos" },
      { slug: "faucets", label: { en: "Faucets & Mixers", es: "Mezcladoras" }, originalPath: "cocina/mezcladoras" },
      { slug: "range-hoods", label: { en: "Range Hoods", es: "Campanas" }, originalPath: "cocina/campanas" },
      { slug: "appliances", label: { en: "Appliances", es: "Electrodomésticos" }, originalPath: "cocina/electrodomesticos" },
      { slug: "soap-dispensers", label: { en: "Soap Dispensers", es: "Dispensadores de Jabón" }, originalPath: "cocina/dispensador-de-jabon" },
      { slug: "water-dispensers", label: { en: "Water Dispensers", es: "Dispensadores de Agua" }, originalPath: "cocina/dispensador-de-agua" },
      { slug: "double-sinks", label: { en: "Double Sinks", es: "Tarja Doble" }, originalPath: "cocina/tarja-doble" },
      { slug: "pot-fillers", label: { en: "Pot Fillers", es: "Llenadores de Ollas" }, originalPath: "cocina/llenador-de-ollas" },
    ],
  },
  hardware: {
    label: { en: "Door Hardware", es: "Chapas y Herrajes" },
    slug: "hardware",
    subcategories: [
      { slug: "door-locks", label: { en: "Door Locks & Lock Sets", es: "Chapas" }, originalPath: "chapas-y-herrajes/chapas" },
      { slug: "deadbolts", label: { en: "Deadbolts", es: "Cerrojos" }, originalPath: "chapas-y-herrajes/cerrojos" },
      { slug: "pulls-hooks", label: { en: "Pulls, Handles & Hooks", es: "Jaladeras y Ganchos" }, originalPath: "chapas-y-herrajes/jaladeras-y-ganchos" },
    ],
  },
} as const;

export type CategoryKey = keyof typeof PRODUCT_CATEGORIES;

// Subcategory hero metadata for subcategory landing pages
export const SUBCATEGORY_META: Record<string, Record<string, {
  heroImage: string;
  description: { en: string; es: string };
}>> = {
  bathroom: {
    sinks: {
      heroImage: "/products/bano/lavabos/Aurora-Cubeta-Niquelado.jpg",
      description: {
        en: "From hand-hammered copper vessels by Mexican artisans to TOTO's precision-engineered undermounts — every basin tells a story.",
        es: "Desde lavabos de cobre martillado a mano por artesanos mexicanos hasta los lavabos de precisión de TOTO — cada pieza cuenta una historia.",
      },
    },
    faucets: {
      heroImage: "/products/bano/grifos/CF-Christopher.jpg",
      description: {
        en: "California Faucets' 30+ artisan finishes, Brizo's industrial precision, and bronze cascades from local coppersmiths — find the perfect pour.",
        es: "Más de 30 acabados artesanales de California Faucets, la precisión industrial de Brizo y cascadas de bronce de artesanos locales — encuentra el grifo perfecto.",
      },
    },
    bathtubs: {
      heroImage: "/products/bano/baneras/Alisia-Niquelado.jpg",
      description: {
        en: "Freestanding soakers by Badeloft, Japanese-depth TOTO designs, and custom stone vessels — the bathtub as sculpture.",
        es: "Bañeras independientes de Badeloft, diseños de profundidad japonesa de TOTO y recipientes de piedra personalizados — la bañera como escultura.",
      },
    },
    "tub-fillers": {
      heroImage: "/products/bano/baneras/Alisia-Niquelado.jpg",
      description: {
        en: "Floor-mounted and wall-mounted tub fillers from California Faucets and Brizo — the finishing touch for your freestanding tub.",
        es: "Llenadores de bañera de piso y pared de California Faucets y Brizo — el toque final para tu bañera independiente.",
      },
    },
    spa: {
      heroImage: "/products/bano/spa/product-1.jpg",
      description: {
        en: "AquaSpa hydrotherapy systems — from intimate two-person tubs to grand outdoor installations with hydrojet massage technology.",
        es: "Sistemas de hidroterapia AquaSpa — desde tinas íntimas para dos personas hasta grandes instalaciones exteriores con tecnología de hidromasaje.",
      },
    },
    toilets: {
      heroImage: "/products/bano/sanitarios/product-1.jpg",
      description: {
        en: "TOTO's WASHLET bidet technology, wall-hung designs, and water-saving engineering — the throne reimagined.",
        es: "Tecnología de bidet WASHLET de TOTO, diseños de pared y ingeniería de ahorro de agua — el trono reimaginado.",
      },
    },
    showers: {
      heroImage: "/products/bano/regaderas/product-1.jpg",
      description: {
        en: "Complete shower systems, rain heads, hand showers, and body sprays from TOTO, California Faucets, and Brizo.",
        es: "Sistemas de ducha completos, regaderas de lluvia, duchas de mano y rociadores corporales de TOTO, California Faucets y Brizo.",
      },
    },
    accessories: {
      heroImage: "/products/accesorios/accesorios-2.png",
      description: {
        en: "Towel bars, robe hooks, toilet paper holders, and hardware accents in 30+ finishes — the details that complete the room.",
        es: "Toalleros, ganchos para batas, portarrollos y acentos de herraje en más de 30 acabados — los detalles que completan la habitación.",
      },
    },
    drains: {
      heroImage: "/products/drenajes/drenajes-2.png",
      description: {
        en: "Ebbe square drains and California Faucets decorative StyleDrain covers — because every detail matters.",
        es: "Drenajes cuadrados Ebbe y cubiertas decorativas StyleDrain de California Faucets — porque cada detalle importa.",
      },
    },
    valves: {
      heroImage: "/products/bano/grifos/CF-Christopher.jpg",
      description: {
        en: "Thermostatic valves, pressure-balancing cartridges, and diverter systems — the precision behind the performance.",
        es: "Válvulas termostáticas, cartuchos de equilibrio de presión y sistemas desviadores — la precisión detrás del rendimiento.",
      },
    },
  },
  kitchen: {
    sinks: {
      heroImage: "/products/cocina/tarjas/Bante-Duetto-Fireclay.png",
      description: {
        en: "BLANCO Silgranit apron sinks, Kohler stainless steel undermounts, and hand-forged copper basins — built to work as hard as you cook.",
        es: "Tarjas con mandil BLANCO Silgranit, fregaderos de acero inoxidable Kohler y lavabos de cobre forjados a mano — hechos para trabajar tan duro como tú cocinas.",
      },
    },
    faucets: {
      heroImage: "/products/cocina/mezcladoras/Brizo-Litze-Angular.png",
      description: {
        en: "Bridge faucets by California Faucets, pull-down designs from Brizo, and professional-grade mixers by ROHL and Delta.",
        es: "Grifos puente de California Faucets, diseños extraíbles de Brizo y mezcladoras de grado profesional de ROHL y Delta.",
      },
    },
    "range-hoods": {
      heroImage: "/products/cocina/electrodomesticos/electrodomesticos-2.png",
      description: {
        en: "Teka German-engineered extraction and decorative island hoods — power and beauty above the cooktop.",
        es: "Extracción de ingeniería alemana Teka y campanas decorativas de isla — potencia y belleza sobre la estufa.",
      },
    },
    appliances: {
      heroImage: "/products/cocina/electrodomesticos/electrodomesticos-2.png",
      description: {
        en: "Professional ranges by Bluestar, SMEG retro ovens, and Teka built-in cooktops — equip your kitchen with the best.",
        es: "Estufas profesionales Bluestar, hornos retro SMEG y parrillas empotradas Teka — equipa tu cocina con lo mejor.",
      },
    },
    "soap-dispensers": {
      heroImage: "/products/accesorios/accesorios-2.png",
      description: {
        en: "Built-in and deck-mounted soap dispensers to match your faucet finish — a clean, seamless countertop.",
        es: "Dispensadores de jabón empotrados y de cubierta para combinar con el acabado de tu grifo — una cubierta limpia y sin interrupciones.",
      },
    },
    "water-dispensers": {
      heroImage: "/products/cocina/mezcladoras/Brizo-Litze-Angular.png",
      description: {
        en: "Hot and filtered water dispensers — instant boiling water at the point of use.",
        es: "Dispensadores de agua caliente y filtrada — agua hirviendo al instante en el punto de uso.",
      },
    },
    "double-sinks": {
      heroImage: "/products/cocina/tarjas/Bante-Duetto-Fireclay.png",
      description: {
        en: "Double-basin configurations for the working kitchen — prep and wash without compromise.",
        es: "Configuraciones de doble tarja para la cocina activa — prepara y lava sin compromisos.",
      },
    },
    "pot-fillers": {
      heroImage: "/products/cocina/mezcladoras/Brizo-Litze-Angular.png",
      description: {
        en: "Wall-mounted pot fillers by California Faucets and Brizo — fill your stockpot right at the stove.",
        es: "Llenadores de ollas de pared de California Faucets y Brizo — llena tu olla directamente en la estufa.",
      },
    },
  },
  hardware: {
    "door-locks": {
      heroImage: "/products/herrajes/chapas-cerrojos/chapas-y-cerrojos-2.png",
      description: {
        en: "Hand-cast silicon bronze entry sets by Sun Valley Bronze and precision-machined Emtek designs — every entrance deserves its own character.",
        es: "Cerraduras de entrada de bronce al silicio fundido a mano de Sun Valley Bronze y diseños de precisión Emtek — cada entrada merece su propio carácter.",
      },
    },
    deadbolts: {
      heroImage: "/products/herrajes/chapas-cerrojos/chapas-y-cerrojos-2.png",
      description: {
        en: "Bronze and brass deadbolts to match your entry set — security that doesn't sacrifice style.",
        es: "Cerrojos de bronce y latón para combinar con tu cerradura de entrada — seguridad que no sacrifica estilo.",
      },
    },
    "pulls-hooks": {
      heroImage: "/products/herrajes/artesanales/artesanales-2.png",
      description: {
        en: "Door knockers, cabinet pulls, coat hooks, and robe hooks in hand-cast bronze and solid brass — the hardware that makes a home.",
        es: "Aldabas, jaladeras de gabinete, ganchos para abrigos y batas en bronce fundido a mano y latón sólido — los herrajes que hacen un hogar.",
      },
    },
  },
};

// Sample product data — will be replaced by Google Sheets API
export const SAMPLE_PRODUCTS = [
  // ─── BATHROOM: SINKS ───
  {
    id: "1",
    sku: "MIST-SURCO-001",
    slug: "mistoa-surco-basin",
    brand: "Mistoa",
    name: "Lavabo Surco",
    nameEn: "Surco Basin",
    category: "bathroom",
    subcategory: "sinks",
    price: 7500,
    currency: "MXN",
    finishes: ["Gris Natural", "Arcilla", "Rosa Crudo", "Durazno", "Mostaza", "Menta", "Azul Somero", "Azul Profundo", "Carbon", "Coco"],
    image: "/products/bano/lavabos/Mistoa-Surco.jpg",
    artisanal: true,
    description: "Lavabo artesanal de concreto por Mistoa, disponible en 10 colores curados inspirados en el paisaje mexicano.",
    descriptionEn: "Handcrafted artisanal concrete basin by Mistoa, available in 10 curated colorways inspired by the Mexican landscape.",
  },
  {
    id: "2",
    sku: "MIST-POAS-001",
    slug: "mistoa-poas-basin",
    brand: "Mistoa",
    name: "Lavabo Poas",
    nameEn: "Poas Basin",
    category: "bathroom",
    subcategory: "sinks",
    price: 8900,
    currency: "MXN",
    finishes: ["Gris Natural", "Arcilla", "Rosa Crudo", "Durazno", "Mostaza", "Menta", "Azul Somero", "Azul Profundo", "Carbon", "Coco"],
    image: "/products/bano/lavabos/Mistoa-Poas.jpg",
    artisanal: true,
    description: "Forma orgánica y tradición artesanal mexicana. Cada lavabo Poas es moldeado y acabado a mano por maestros artesanos.",
    descriptionEn: "Organic form meets Mexican craft tradition. Each Poas basin is hand-shaped and finished by master artisans.",
  },
  {
    id: "3",
    sku: "TOTO-AIMES-001",
    slug: "toto-aimes-undermount",
    brand: "TOTO",
    name: "Aimes® Lavabo Submontar",
    nameEn: "Aimes® Undermount Lavatory",
    category: "bathroom",
    subcategory: "sinks",
    price: 12316,
    currency: "MXN",
    finishes: ["Algodón", "Hueso", "Blanco Colonial", "Beige Sedona", "Ebony"],
    image: "/products/bano/lavabos/TOTO-Aimes-Lavabo.png",
    artisanal: false,
    description: "El lavabo Aimes de TOTO combina geometría refinada con tecnología de esmalte cerámico CEFIONTECT.",
    descriptionEn: "TOTO's Aimes undermount lavatory combines refined geometry with CEFIONTECT ceramic glaze technology.",
  },
  {
    id: "4",
    sku: "CC-MICHELLE-001",
    slug: "michelle-polished-copper-vessel",
    brand: "Counter Cultures",
    name: "Michelle Vessel Cobre Brillado",
    nameEn: "Michelle Polished Copper Vessel",
    category: "bathroom",
    subcategory: "sinks",
    price: 5156,
    currency: "MXN",
    finishes: ["Cobre Brillado"],
    image: "/products/bano/lavabos/Michelle-Vessel-Cobre.jpg",
    artisanal: true,
    description: "Lavabo vessel de cobre brillado martillado a mano, diseñado por Roger Williams y fabricado por artesanos cobreros mexicanos.",
    descriptionEn: "Hand-hammered polished copper vessel sink, designed by Roger Williams and crafted by Mexican coppersmiths.",
  },
  {
    id: "5",
    sku: "CC-ELOY-001",
    slug: "eloy-copper-basin",
    brand: "Counter Cultures",
    name: "Eloy Lavabo de Cobre",
    nameEn: "Eloy Copper Basin",
    category: "bathroom",
    subcategory: "sinks",
    price: 8923,
    currency: "MXN",
    finishes: ["Hammered Copper", "Cobre Oscuro"],
    image: "/products/bano/lavabos/Eloy-Lavabo-Cobre.png",
    artisanal: true,
    description: "Lavabo rectangular de cobre martillado, forjado a mano por artesanos mexicanos. Cada pieza lleva las marcas únicas de su creador.",
    descriptionEn: "Rectangular hammered copper basin, hand-forged by Mexican artisans. Each piece carries the unique marks of its maker.",
  },
  {
    id: "6",
    sku: "BDL-VESSEL-COP",
    slug: "badeloft-copper-vessel",
    brand: "Badeloft",
    name: "Lavabo Vessel Cobre",
    nameEn: "Copper Vessel Sink",
    category: "bathroom",
    subcategory: "sinks",
    price: 3278,
    currency: "MXN",
    finishes: ["Copper", "Antique Copper"],
    image: "/products/bano/baneras/Badeloft-BW-02-S.jpg",
    artisanal: false,
    description: "Lavabo vessel de cobre de Badeloft — forma clásica con acabado de cobre envejecido o natural.",
    descriptionEn: "Badeloft copper vessel sink — classic form with aged or natural copper finish.",
  },
  // ─── BATHROOM: FAUCETS ───
  {
    id: "7",
    sku: "CF-CHRIS-001",
    slug: "california-faucets-christopher",
    brand: "California Faucets",
    name: "Grifo Christopher",
    nameEn: "Christopher Single-Hole Faucet",
    category: "bathroom",
    subcategory: "faucets",
    price: 12450,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Antique Brass", "Oil Rubbed Bronze", "Matte Black", "Burnished Brass"],
    image: "/products/bano/grifos/CF-Christopher.jpg",
    artisanal: false,
    description: "Grifo monomando Christopher de California Faucets — disponible en más de 30 acabados artesanales.",
    descriptionEn: "California Faucets Christopher single-hole faucet — available in 30+ artisan finishes, handcrafted in Huntington Beach.",
  },
  {
    id: "8",
    sku: "CF-STEAM-001",
    slug: "california-faucets-steampunk-bay",
    brand: "California Faucets",
    name: "Grifo Steampunk Bay",
    nameEn: "Steampunk Bay Widespread Faucet",
    category: "bathroom",
    subcategory: "faucets",
    price: 58985,
    currency: "MXN",
    finishes: ["Antique Brass", "Carbon", "Weathered Copper", "Satin Nickel"],
    image: "/products/bano/grifos/CF-SteampunkBay.jpg",
    artisanal: false,
    description: "Grifo de 3 orificios Steampunk Bay — diseño industrial con ruedas de engranaje, pieza de declaración.",
    descriptionEn: "Steampunk Bay 3-hole widespread faucet — industrial design with gear wheel handles, a true statement piece.",
  },
  {
    id: "9",
    sku: "CF-DESCANSO-001",
    slug: "california-faucets-descanso",
    brand: "California Faucets",
    name: "Grifo Descanso",
    nameEn: "Descanso Single-Hole Faucet",
    category: "bathroom",
    subcategory: "faucets",
    price: 8750,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Matte Black", "Burnished Brass", "Polished Nickel"],
    image: "/products/bano/grifos/CF-Descanso-Mango.jpg",
    artisanal: false,
    description: "Grifo monomando Descanso con mango de nudos de cuerda — elegancia náutica para el baño.",
    descriptionEn: "Descanso single-hole faucet with knurled rope handle — nautical elegance for the bath.",
  },
  {
    id: "10",
    sku: "BRIZO-ROOK-001",
    slug: "brizo-rook-faucet",
    brand: "Brizo",
    name: "Grifo Rook Monomando",
    nameEn: "Rook Single-Handle Faucet",
    category: "bathroom",
    subcategory: "faucets",
    price: 18500,
    currency: "MXN",
    finishes: ["Chrome", "Matte Black", "Luxe Gold", "Brilliance Polished Nickel"],
    image: "/products/cocina/mezcladoras/Brizo-Litze-Angular.png",
    artisanal: false,
    description: "Grifo monomando Rook de Brizo — líneas arquitectónicas con detalles facetados inspirados en puentes históricos.",
    descriptionEn: "Brizo Rook single-handle faucet — architectural lines with faceted detailing inspired by historic bridges.",
  },
  {
    id: "11",
    sku: "CC-WATERFALL-001",
    slug: "artisan-bronze-waterfall-faucet",
    brand: "Counter Cultures",
    name: "Grifo Cascada Bronce Artesanal",
    nameEn: "Artisan Bronze Waterfall Faucet",
    category: "bathroom",
    subcategory: "faucets",
    price: 14765,
    currency: "MXN",
    finishes: ["Natural Bronze", "Dark Bronze"],
    image: "/products/herrajes/artesanales/product-1.jpg",
    artisanal: true,
    description: "Grifo de cascada de bronce fundido a mano por artesanos locales — flujo de agua tipo cascada con pátina viva.",
    descriptionEn: "Hand-cast bronze waterfall faucet by local artisans — cascading water flow with living patina.",
  },
  // ─── BATHROOM: BATHTUBS ───
  {
    id: "12",
    sku: "BDL-FREE-001",
    slug: "badeloft-freestanding-bathtub",
    brand: "Badeloft",
    name: "Bañera Independiente",
    nameEn: "Freestanding Bathtub",
    category: "bathroom",
    subcategory: "bathtubs",
    price: 45000,
    currency: "MXN",
    finishes: ["Glossy White", "Matte White"],
    image: "/products/bano/baneras/Badeloft-BW-02-S.jpg",
    artisanal: false,
    description: "Bañera independiente Badeloft — fundición mineral sin costuras, forma ergonómica, superficie fácil de limpiar.",
    descriptionEn: "Badeloft freestanding soaking tub — seamless mineral casting, ergonomic form, easy-clean surface.",
  },
  {
    id: "13",
    sku: "BDL-OVAL-001",
    slug: "badeloft-oval-soaker",
    brand: "Badeloft",
    name: "Bañera Oval Independiente",
    nameEn: "Oval Freestanding Soaker",
    category: "bathroom",
    subcategory: "bathtubs",
    price: 52000,
    currency: "MXN",
    finishes: ["Glossy White", "Matte White", "Matte Grey"],
    image: "/products/bano/baneras/Badeloft-BW-02-S.jpg",
    artisanal: false,
    description: "Bañera oval independiente con capacidad de inmersión profunda — piedra compuesta con acabado sedoso.",
    descriptionEn: "Oval freestanding soaker with deep immersion capacity — composite stone with silky finish.",
  },
  // ─── BATHROOM: TUB FILLERS ───
  {
    id: "14",
    sku: "CF-TUBFILL-001",
    slug: "california-faucets-floor-mount-tub-filler",
    brand: "California Faucets",
    name: "Llenador de Bañera de Piso",
    nameEn: "Floor-Mount Tub Filler",
    category: "bathroom",
    subcategory: "tub-fillers",
    price: 34500,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Matte Black", "Burnished Brass"],
    image: "/products/bano/regaderas/product-1.jpg",
    artisanal: false,
    description: "Llenador de bañera de piso California Faucets con ducha de mano — acabado artesanal, instalación independiente.",
    descriptionEn: "California Faucets floor-mount tub filler with hand shower — artisan finish, freestanding installation.",
  },
  {
    id: "15",
    sku: "BRIZO-TUBFILL-001",
    slug: "brizo-wall-mount-tub-filler",
    brand: "Brizo",
    name: "Llenador de Bañera de Pared",
    nameEn: "Wall-Mount Tub Filler",
    category: "bathroom",
    subcategory: "tub-fillers",
    price: 28900,
    currency: "MXN",
    finishes: ["Chrome", "Matte Black", "Luxe Gold"],
    image: "/products/bano/regaderas/product-1.jpg",
    artisanal: false,
    description: "Llenador de bañera de pared Brizo — diseño minimalista con alto flujo para llenado rápido.",
    descriptionEn: "Brizo wall-mount tub filler — minimalist design with high flow for rapid filling.",
  },
  // ─── BATHROOM: SPA ───
  {
    id: "16",
    sku: "AQS-VELAS-001",
    slug: "aquaspa-velas",
    brand: "AquaSpa",
    name: "Spa Velas",
    nameEn: "Velas Hydrotherapy Spa",
    category: "bathroom",
    subcategory: "spa",
    price: 133565,
    currency: "MXN",
    finishes: ["White Shell", "Sandstone"],
    image: "/products/bano/spa/product-1.jpg",
    artisanal: false,
    description: "Sistema de hidroterapia AquaSpa Velas — jets de hidromasaje, iluminación LED, capacidad para 2 personas.",
    descriptionEn: "AquaSpa Velas hydrotherapy system — hydrojet massage, LED lighting, 2-person capacity.",
  },
  {
    id: "17",
    sku: "AQS-CABO-001",
    slug: "aquaspa-cabo",
    brand: "AquaSpa",
    name: "Spa Cabo",
    nameEn: "Cabo Hydrotherapy Spa",
    category: "bathroom",
    subcategory: "spa",
    price: 198750,
    currency: "MXN",
    finishes: ["White Shell", "Graphite"],
    image: "/products/bano/spa/product-1.jpg",
    artisanal: false,
    description: "Spa de hidroterapia AquaSpa Cabo — instalación exterior, 4 personas, sistema de jets programables.",
    descriptionEn: "AquaSpa Cabo hydrotherapy spa — outdoor installation, 4-person, programmable jet system.",
  },
  {
    id: "18",
    sku: "AQS-PARADISE-001",
    slug: "aquaspa-paradise",
    brand: "AquaSpa",
    name: "Spa Paradise",
    nameEn: "Paradise Hydrotherapy Spa",
    category: "bathroom",
    subcategory: "spa",
    price: 289362,
    currency: "MXN",
    finishes: ["White Shell", "Midnight Blue"],
    image: "/products/bano/spa/product-1.jpg",
    artisanal: false,
    description: "Spa de hidroterapia AquaSpa Paradise — modelo insignia, 6 personas, cascada, iluminación cromática.",
    descriptionEn: "AquaSpa Paradise hydrotherapy spa — flagship model, 6-person, waterfall feature, chromatherapy lighting.",
  },
  // ─── BATHROOM: TOILETS ───
  {
    id: "19",
    sku: "TOTO-CONNELLY-001",
    slug: "toto-connelly-two-piece",
    brand: "TOTO",
    name: "Connelly Sanitario Dos Piezas",
    nameEn: "Connelly Two-Piece Toilet",
    category: "bathroom",
    subcategory: "toilets",
    price: 22500,
    currency: "MXN",
    finishes: ["Cotton White", "Bone", "Colonial White", "Sedona Beige"],
    image: "/products/bano/sanitarios/product-1.jpg",
    artisanal: false,
    description: "Sanitario de dos piezas TOTO Connelly — doble descarga, CEFIONTECT, diseño contemporáneo.",
    descriptionEn: "TOTO Connelly two-piece toilet — dual flush, CEFIONTECT glaze, contemporary skirted design.",
  },
  {
    id: "20",
    sku: "TOTO-DRAKE-001",
    slug: "toto-drake-elongated",
    brand: "TOTO",
    name: "Drake Sanitario Elongado",
    nameEn: "Drake Elongated Toilet",
    category: "bathroom",
    subcategory: "toilets",
    price: 15800,
    currency: "MXN",
    finishes: ["Cotton White", "Bone", "Colonial White"],
    image: "/products/bano/sanitarios/product-1.jpg",
    artisanal: false,
    description: "Sanitario elongado TOTO Drake — sistema Tornado Flush, 1.28 GPF, el más vendido de TOTO.",
    descriptionEn: "TOTO Drake elongated toilet — Tornado Flush system, 1.28 GPF, TOTO's best-selling model.",
  },
  {
    id: "21",
    sku: "TOTO-WASHLET-S7A",
    slug: "toto-washlet-s7a",
    brand: "TOTO",
    name: "WASHLET S7A Asiento Bidet",
    nameEn: "WASHLET S7A Bidet Seat",
    category: "bathroom",
    subcategory: "toilets",
    price: 103588,
    currency: "MXN",
    finishes: ["Cotton White"],
    image: "/products/bano/sanitarios/product-1.jpg",
    artisanal: false,
    description: "Asiento bidet WASHLET S7A — EWATER+, secado con aire caliente, desodorizador, apertura automática, control remoto.",
    descriptionEn: "WASHLET S7A bidet seat — EWATER+, warm air dryer, deodorizer, auto open/close lid, wireless remote.",
    specifications: { "Water Temp": "3 settings", "Dryer": "Yes", "Deodorizer": "Yes", "Auto Lid": "Yes", "Remote": "Wireless" },
  },
  {
    id: "22",
    sku: "TOTO-WASHLET-C5",
    slug: "toto-washlet-c5",
    brand: "TOTO",
    name: "WASHLET C5 Asiento Bidet",
    nameEn: "WASHLET C5 Bidet Seat",
    category: "bathroom",
    subcategory: "toilets",
    price: 13177,
    currency: "MXN",
    finishes: ["Cotton White"],
    image: "/products/bano/sanitarios/product-1.jpg",
    artisanal: false,
    description: "Asiento bidet WASHLET C5 — lavado posterior y frontal, asiento calefaccionado, PREMIST.",
    descriptionEn: "WASHLET C5 bidet seat — rear and front wash, heated seat, PREMIST technology.",
  },
  // ─── BATHROOM: SHOWERS ───
  {
    id: "23",
    sku: "CF-SHOWER-001",
    slug: "california-faucets-shower-system",
    brand: "California Faucets",
    name: "Sistema de Ducha StyleTherm",
    nameEn: "StyleTherm Shower System",
    category: "bathroom",
    subcategory: "showers",
    price: 42000,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Matte Black", "Burnished Brass"],
    image: "/products/bano/regaderas/product-1.jpg",
    artisanal: false,
    description: "Sistema de ducha termostático StyleTherm de California Faucets — regadera de lluvia, ducha de mano, rociadores corporales.",
    descriptionEn: "California Faucets StyleTherm thermostatic shower system — rain head, hand shower, body sprays.",
  },
  {
    id: "24",
    sku: "BRIZO-SHOWER-001",
    slug: "brizo-sensori-shower",
    brand: "Brizo",
    name: "Regadera Sensori",
    nameEn: "Sensori Shower Head",
    category: "bathroom",
    subcategory: "showers",
    price: 15600,
    currency: "MXN",
    finishes: ["Chrome", "Matte Black", "Luxe Gold"],
    image: "/products/bano/regaderas/product-1.jpg",
    artisanal: false,
    description: "Regadera Sensori de Brizo — tecnología H2Okinetic para cobertura amplia con menor consumo de agua.",
    descriptionEn: "Brizo Sensori shower head — H2Okinetic technology for wide coverage with less water consumption.",
  },
  // ─── BATHROOM: ACCESSORIES ───
  {
    id: "25",
    sku: "CF-TOWEL24-001",
    slug: "california-faucets-towel-bar-24",
    brand: "California Faucets",
    name: "Toallero 24 Pulgadas",
    nameEn: "24\" Towel Bar",
    category: "bathroom",
    subcategory: "accessories",
    price: 6450,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Matte Black", "Burnished Brass", "Oil Rubbed Bronze"],
    image: "/products/accesorios/product-1.jpg",
    artisanal: false,
    description: "Toallero de 24 pulgadas de California Faucets — disponible en más de 30 acabados artesanales.",
    descriptionEn: "California Faucets 24\" towel bar — available in 30+ artisan finishes.",
  },
  {
    id: "26",
    sku: "CF-HOOK-001",
    slug: "california-faucets-robe-hook",
    brand: "California Faucets",
    name: "Gancho para Bata",
    nameEn: "Robe Hook",
    category: "bathroom",
    subcategory: "accessories",
    price: 2396,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Matte Black", "Burnished Brass"],
    image: "/products/accesorios/product-1.jpg",
    artisanal: false,
    description: "Gancho para bata de California Faucets — diseño limpio, sólida construcción de latón.",
    descriptionEn: "California Faucets robe hook — clean design, solid brass construction.",
  },
  {
    id: "27",
    sku: "CF-TP-001",
    slug: "california-faucets-toilet-paper-holder",
    brand: "California Faucets",
    name: "Portarrollos",
    nameEn: "Toilet Paper Holder",
    category: "bathroom",
    subcategory: "accessories",
    price: 3670,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Matte Black", "Burnished Brass", "Oil Rubbed Bronze"],
    image: "/products/accesorios/product-1.jpg",
    artisanal: false,
    description: "Portarrollos de California Faucets — brazo articulado, acabados coordinados con toda la línea.",
    descriptionEn: "California Faucets toilet paper holder — pivoting arm, finishes matched across the full line.",
  },
  // ─── BATHROOM: DRAINS ───
  {
    id: "28",
    sku: "EBBE-LATTICE-001",
    slug: "ebbe-lattice-drain",
    brand: "Ebbe",
    name: "Drenaje Lattice",
    nameEn: "Lattice Square Drain",
    category: "bathroom",
    subcategory: "drains",
    price: 2845,
    currency: "MXN",
    finishes: ["Brushed Stainless", "Oil Rubbed Bronze", "Polished Chrome", "Matte Black"],
    image: "/products/drenajes/product-1.jpg",
    artisanal: false,
    description: "Drenaje cuadrado Ebbe Lattice — patrón de celosía, acero inoxidable, instalación a ras de piso.",
    descriptionEn: "Ebbe Lattice square drain — lattice pattern, stainless steel, flush-mount installation.",
  },
  {
    id: "29",
    sku: "CF-STYLEDRAIN-001",
    slug: "california-faucets-styledrain-neo",
    brand: "California Faucets",
    name: "StyleDrain Neo",
    nameEn: "StyleDrain Neo Decorative Drain",
    category: "bathroom",
    subcategory: "drains",
    price: 6413,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Matte Black", "Burnished Brass"],
    image: "/products/drenajes/product-1.jpg",
    artisanal: false,
    description: "Cubierta decorativa StyleDrain Neo de California Faucets — diseño geométrico moderno, 30+ acabados.",
    descriptionEn: "California Faucets StyleDrain Neo decorative cover — modern geometric design, 30+ finishes.",
  },
  {
    id: "30",
    sku: "EBBE-QUADRA-001",
    slug: "ebbe-quadra-drain",
    brand: "Ebbe",
    name: "Drenaje Quadra",
    nameEn: "Quadra Square Drain",
    category: "bathroom",
    subcategory: "drains",
    price: 428,
    currency: "MXN",
    finishes: ["Brushed Stainless", "Polished Chrome"],
    image: "/products/drenajes/product-1.jpg",
    artisanal: false,
    description: "Drenaje cuadrado Ebbe Quadra — diseño minimalista, precio accesible, acero inoxidable.",
    descriptionEn: "Ebbe Quadra square drain — minimalist design, accessible price point, stainless steel.",
  },
  // ─── BATHROOM: VALVES ───
  {
    id: "31",
    sku: "CF-VALVE-THERM",
    slug: "california-faucets-thermostatic-valve",
    brand: "California Faucets",
    name: "Válvula Termostática StyleTherm",
    nameEn: "StyleTherm Thermostatic Valve",
    category: "bathroom",
    subcategory: "valves",
    price: 18900,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Matte Black"],
    image: "/products/accesorios/product-1.jpg",
    artisanal: false,
    description: "Válvula termostática StyleTherm — control preciso de temperatura, sistema anti-escaldadura integrado.",
    descriptionEn: "StyleTherm thermostatic valve — precise temperature control, integrated anti-scald system.",
  },
  {
    id: "32",
    sku: "CF-VALVE-DIV",
    slug: "california-faucets-diverter-valve",
    brand: "California Faucets",
    name: "Válvula Desviadora",
    nameEn: "Diverter Valve",
    category: "bathroom",
    subcategory: "valves",
    price: 8500,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Matte Black"],
    image: "/products/accesorios/product-1.jpg",
    artisanal: false,
    description: "Válvula desviadora California Faucets — controla hasta 3 salidas de agua independientes.",
    descriptionEn: "California Faucets diverter valve — controls up to 3 independent water outlets.",
  },
  // ─── KITCHEN: SINKS ───
  {
    id: "33",
    sku: "BLN-IKON-30",
    slug: "blanco-ikon-30-apron-sink",
    brand: "BLANCO",
    name: "Ikon Silgranit Con Mandil 30\"",
    nameEn: "Ikon 30\" Silgranit Apron Sink",
    category: "kitchen",
    subcategory: "sinks",
    price: 39341,
    currency: "MXN",
    finishes: ["Anthracite", "Blanco", "Cinder", "Truffle", "Gris Metálico", "Café", "Gris Volcánico", "Coal Negro"],
    image: "/products/cocina/tarjas/Blanco-Ikon-Silgranit.jpg",
    artisanal: false,
    description: "Tarja con mandil BLANCO Ikon en Silgranit patentado — resistente al calor, rayaduras y manchas.",
    descriptionEn: "BLANCO's iconic apron front sink in patented Silgranit material — heat, scratch, and stain resistant.",
  },
  {
    id: "34",
    sku: "KOH-STRIVE-24",
    slug: "kohler-strive-24-sink",
    brand: "Kohler",
    name: "Strive Fregadero 24\"",
    nameEn: "Strive 24\" Undermount Kitchen Sink",
    category: "kitchen",
    subcategory: "sinks",
    price: 17726,
    currency: "MXN",
    finishes: ["Stainless Steel"],
    image: "/products/cocina/tarjas/Blanco-Ikon-Silgranit.jpg",
    artisanal: false,
    description: "Fregadero de bajo montar Strive de Kohler — esquinas de radio cerrado, tecnología SilentShield.",
    descriptionEn: "Kohler's Strive undermount single-basin kitchen sink — tight radius corners, SilentShield technology.",
  },
  {
    id: "35",
    sku: "KOH-BROCKWAY-36",
    slug: "kohler-brockway-36-wall-mount",
    brand: "Kohler",
    name: "Brockway Fregadero Mural 36\"",
    nameEn: "Brockway 36\" Wall-Mounted Sink",
    category: "kitchen",
    subcategory: "sinks",
    price: 44919,
    currency: "MXN",
    finishes: ["White"],
    image: "/products/cocina/tarjas/Blanco-Ikon-Silgranit.jpg",
    artisanal: false,
    description: "Fregadero mural Brockway de 36\" — diseño industrial inspirado en granjas, hierro fundido esmaltado.",
    descriptionEn: "Brockway 36\" wall-mounted sink — industrial farmhouse design, enameled cast iron.",
  },
  {
    id: "36",
    sku: "BNT-DUO-001",
    slug: "bante-tarja-duo",
    brand: "Banté",
    name: "Tarja Duo Cerámica",
    nameEn: "Tarja Duo Ceramic Sink",
    category: "kitchen",
    subcategory: "sinks",
    price: 22870,
    currency: "MXN",
    finishes: ["White", "Biscuit"],
    image: "/products/cocina/tarjas/Bante-Tarja-Duo.png",
    artisanal: false,
    description: "Tarja doble de cerámica Banté Duo — diseño clásico con borde elevado y acabado esmaltado duradero.",
    descriptionEn: "Banté Tarja Duo ceramic double sink — classic design with raised rim and durable glazed finish.",
  },
  {
    id: "37",
    sku: "CC-ISLAND-BRASS",
    slug: "artisanal-hammered-brass-island-sink",
    brand: "Counter Cultures",
    name: "Tarja Artesanal Latón Martillado",
    nameEn: "Artisanal Hammered Brass Island Sink",
    category: "kitchen",
    subcategory: "sinks",
    price: 9943,
    currency: "MXN",
    finishes: ["Hammered Brass", "Hammered Copper"],
    image: "/products/cocina/tarjas/Tarja-Laton-Martillado.jpg",
    artisanal: true,
    description: "Tarja de latón martillado a mano para isla de cocina — cada pieza hecha por artesanos de Santa Clara del Cobre.",
    descriptionEn: "Hand-hammered brass island sink — each piece crafted by artisans from Santa Clara del Cobre.",
  },
  // ─── KITCHEN: FAUCETS ───
  {
    id: "38",
    sku: "BRIZO-LITZE-001",
    slug: "brizo-litze-pull-down",
    brand: "Brizo",
    name: "Litze Mezcladora Extraíble",
    nameEn: "Litze Pull-Down Kitchen Faucet",
    category: "kitchen",
    subcategory: "faucets",
    price: 28500,
    currency: "MXN",
    finishes: ["Chrome", "Matte Black", "Polished Nickel", "Luxe Gold"],
    image: "/products/cocina/mezcladoras/Brizo-Litze-SmartTouch.png",
    artisanal: false,
    description: "Mezcladora de cocina Litze de Brizo — resortes expuestos, juntas articuladas, diseño puente que convierte tu fregadero en pieza central.",
    descriptionEn: "Brizo Litze pull-down kitchen faucet — exposed springs, articulating joints, bridge design that turns your sink into a statement.",
  },
  {
    id: "39",
    sku: "CF-BRIDGE-001",
    slug: "california-faucets-davoli-bridge",
    brand: "California Faucets",
    name: "Mezcladora Puente Davoli",
    nameEn: "Davoli Bridge Kitchen Faucet",
    category: "kitchen",
    subcategory: "faucets",
    price: 22000,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Antique Brass", "Oil Rubbed Bronze", "Matte Black"],
    image: "/products/cocina/mezcladoras/CF-Davoli-Bridge.jpg",
    artisanal: false,
    description: "Mezcladora puente Davoli de California Faucets — hecha a mano en Huntington Beach, CA con más de 30 opciones de acabado.",
    descriptionEn: "California Faucets Davoli bridge kitchen faucet — handcrafted in Huntington Beach, CA with over 30 finish options.",
  },
  {
    id: "40",
    sku: "ROHL-BRIDGE-001",
    slug: "rohl-bridge-faucet",
    brand: "ROHL",
    name: "Mezcladora Puente Clásica",
    nameEn: "Classic Bridge Kitchen Faucet",
    category: "kitchen",
    subcategory: "faucets",
    price: 35800,
    currency: "MXN",
    finishes: ["Polished Nickel", "English Bronze", "Polished Chrome", "Satin Nickel"],
    image: "/products/cocina/mezcladoras/Rohl-Georgiana.png",
    artisanal: false,
    description: "Mezcladora puente ROHL — diseño clásico con rociador lateral, construcción de latón sólido.",
    descriptionEn: "ROHL classic bridge kitchen faucet — traditional design with side spray, solid brass construction.",
  },
  {
    id: "41",
    sku: "DELTA-TRINSIC-001",
    slug: "delta-trinsic-pull-down",
    brand: "Delta",
    name: "Trinsic Mezcladora Extraíble",
    nameEn: "Trinsic Pull-Down Kitchen Faucet",
    category: "kitchen",
    subcategory: "faucets",
    price: 4225,
    currency: "MXN",
    finishes: ["Chrome", "Matte Black", "Stainless", "Champagne Bronze"],
    image: "/products/cocina/mezcladoras/Delta-Trinsic.png",
    artisanal: false,
    description: "Mezcladora Trinsic de Delta — diseño esbelto, tecnología MagnaTite para acoplamiento magnético del rociador.",
    descriptionEn: "Delta Trinsic pull-down kitchen faucet — sleek design, MagnaTite docking for magnetic sprayer hold.",
  },
  // ─── KITCHEN: RANGE HOODS ───
  {
    id: "42",
    sku: "TEKA-GFH73",
    slug: "teka-gfh-73-hood",
    brand: "Teka",
    name: "Campana GFH 73",
    nameEn: "GFH 73 Range Hood",
    category: "kitchen",
    subcategory: "range-hoods",
    price: 8199,
    currency: "MXN",
    finishes: ["Stainless Steel"],
    image: "/products/cocina/electrodomesticos/product-1.jpg",
    artisanal: false,
    description: "Campana extractora Teka GFH 73 — ingeniería alemana, 3 velocidades, filtros de aluminio lavables.",
    descriptionEn: "Teka GFH 73 range hood — German-engineered, 3 speeds, washable aluminum filters.",
  },
  {
    id: "43",
    sku: "TEKA-DG980",
    slug: "teka-dg-980-hood",
    brand: "Teka",
    name: "Campana DG 980",
    nameEn: "DG 980 Decorative Hood",
    category: "kitchen",
    subcategory: "range-hoods",
    price: 13799,
    currency: "MXN",
    finishes: ["Stainless Steel", "Black Glass"],
    image: "/products/cocina/electrodomesticos/product-1.jpg",
    artisanal: false,
    description: "Campana decorativa Teka DG 980 — diseño de pared, panel de vidrio, motor de alta eficiencia.",
    descriptionEn: "Teka DG 980 decorative wall hood — glass panel design, high-efficiency motor.",
  },
  {
    id: "44",
    sku: "TEKA-ISLAND-001",
    slug: "teka-island-hood-touch",
    brand: "Teka",
    name: "Campana Isla con Control Táctil",
    nameEn: "Island Hood with Touch Controls",
    category: "kitchen",
    subcategory: "range-hoods",
    price: 31599,
    currency: "MXN",
    finishes: ["Stainless Steel"],
    image: "/products/cocina/electrodomesticos/product-1.jpg",
    artisanal: false,
    description: "Campana de isla decorativa Teka — controles táctiles, iluminación LED perimetral, 4 velocidades.",
    descriptionEn: "Teka decorative island hood — touch controls, perimeter LED lighting, 4 speeds.",
  },
  // ─── KITCHEN: APPLIANCES ───
  {
    id: "45",
    sku: "BSTAR-RANGE-001",
    slug: "bluestar-platinum-range",
    brand: "Bluestar",
    name: "Estufa Platinum Series",
    nameEn: "Platinum Series Gas Range",
    category: "kitchen",
    subcategory: "appliances",
    price: 224746,
    currency: "MXN",
    finishes: ["Stainless Steel", "Custom RAL Colors"],
    image: "/products/cocina/electrodomesticos/product-1.jpg",
    artisanal: false,
    description: "Estufa de gas Bluestar Platinum Series — quemadores de 25,000 BTU, horno de convección, acabados personalizables.",
    descriptionEn: "Bluestar Platinum Series gas range — 25,000 BTU burners, convection oven, customizable colors.",
    specifications: { "BTU": "25,000 per burner", "Oven": "Convection", "Width": "36\"", "Fuel": "Natural Gas / LP" },
  },
  {
    id: "46",
    sku: "SMEG-RETRO-001",
    slug: "smeg-retro-oven",
    brand: "SMEG",
    name: "Horno Retro Victoria",
    nameEn: "Victoria Retro Oven",
    category: "kitchen",
    subcategory: "appliances",
    price: 48500,
    currency: "MXN",
    finishes: ["Cream", "Black", "Red", "Pastel Blue"],
    image: "/products/cocina/electrodomesticos/product-1.jpg",
    artisanal: false,
    description: "Horno SMEG Victoria — estilo retro icónico, múltiples funciones de cocción, acabado esmaltado.",
    descriptionEn: "SMEG Victoria retro oven — iconic retro styling, multiple cooking functions, enamel finish.",
  },
  {
    id: "47",
    sku: "TEKA-COOKTOP-001",
    slug: "teka-gas-cooktop",
    brand: "Teka",
    name: "Parrilla de Gas Empotrada",
    nameEn: "Built-In Gas Cooktop",
    category: "kitchen",
    subcategory: "appliances",
    price: 13698,
    currency: "MXN",
    finishes: ["Stainless Steel", "Black Glass"],
    image: "/products/cocina/electrodomesticos/product-1.jpg",
    artisanal: false,
    description: "Parrilla de gas empotrada Teka — 5 quemadores, encendido electrónico, parrillas de hierro fundido.",
    descriptionEn: "Teka built-in gas cooktop — 5 burners, electronic ignition, cast iron grates.",
  },
  // ─── KITCHEN: SOAP DISPENSERS ───
  {
    id: "48",
    sku: "CF-SOAP-001",
    slug: "california-faucets-soap-dispenser",
    brand: "California Faucets",
    name: "Dispensador de Jabón Empotrado",
    nameEn: "Built-In Soap Dispenser",
    category: "kitchen",
    subcategory: "soap-dispensers",
    price: 4200,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Matte Black", "Burnished Brass"],
    image: "/products/accesorios/product-1.jpg",
    artisanal: false,
    description: "Dispensador de jabón empotrado California Faucets — acabado coordinado con toda la línea de grifería.",
    descriptionEn: "California Faucets built-in soap dispenser — finish matched across the full faucet line.",
  },
  // ─── KITCHEN: WATER DISPENSERS ───
  {
    id: "49",
    sku: "CF-WATER-001",
    slug: "california-faucets-hot-water-dispenser",
    brand: "California Faucets",
    name: "Dispensador de Agua Caliente",
    nameEn: "Hot Water Dispenser",
    category: "kitchen",
    subcategory: "water-dispensers",
    price: 7800,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Matte Black"],
    image: "/products/accesorios/product-1.jpg",
    artisanal: false,
    description: "Dispensador de agua caliente instantánea California Faucets — tanque incluido, agua a 200°F al instante.",
    descriptionEn: "California Faucets instant hot water dispenser — tank included, 200°F water on demand.",
  },
  // ─── KITCHEN: DOUBLE SINKS ───
  {
    id: "50",
    sku: "BLN-IKON-DOUBLE",
    slug: "blanco-ikon-double-bowl",
    brand: "BLANCO",
    name: "Ikon Silgranit Doble Tarja",
    nameEn: "Ikon Silgranit Double Bowl Sink",
    category: "kitchen",
    subcategory: "double-sinks",
    price: 43897,
    currency: "MXN",
    finishes: ["Anthracite", "Blanco", "Cinder", "Truffle"],
    image: "/products/cocina/tarjas/Blanco-Diamond-Doble.jpg",
    artisanal: false,
    description: "Tarja doble BLANCO Ikon en Silgranit — división baja para piezas grandes, mandil frontal integrado.",
    descriptionEn: "BLANCO Ikon double bowl in Silgranit — low divide for large items, integrated apron front.",
  },
  // ─── KITCHEN: POT FILLERS ───
  {
    id: "51",
    sku: "CF-POTFILL-001",
    slug: "california-faucets-pot-filler",
    brand: "California Faucets",
    name: "Llenador de Ollas de Pared",
    nameEn: "Wall-Mount Pot Filler",
    category: "kitchen",
    subcategory: "pot-fillers",
    price: 18500,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Matte Black", "Burnished Brass", "Oil Rubbed Bronze"],
    image: "/products/cocina/mezcladoras/CF-Poetto.jpg",
    artisanal: false,
    description: "Llenador de ollas de pared California Faucets — brazo articulado doble, 30+ acabados.",
    descriptionEn: "California Faucets wall-mount pot filler — dual-articulating arm, 30+ finishes.",
  },
  {
    id: "52",
    sku: "BRIZO-POTFILL-001",
    slug: "brizo-artesso-pot-filler",
    brand: "Brizo",
    name: "Artesso Llenador de Ollas",
    nameEn: "Artesso Pot Filler",
    category: "kitchen",
    subcategory: "pot-fillers",
    price: 24800,
    currency: "MXN",
    finishes: ["Chrome", "Matte Black", "Luxe Gold"],
    image: "/products/cocina/mezcladoras/Brizo-Litze-Angular.png",
    artisanal: false,
    description: "Llenador de ollas Artesso de Brizo — diseño artesanal con detalles de remache y brazo extensible.",
    descriptionEn: "Brizo Artesso pot filler — artisan design with rivet detailing and extending arm.",
  },
  // ─── HARDWARE: DOOR LOCKS ───
  {
    id: "53",
    sku: "SVB-ENTRY-CONT",
    slug: "sun-valley-bronze-contemporary-entry",
    brand: "Sun Valley Bronze",
    name: "Cerradura Entrada Contemporary",
    nameEn: "Contemporary Entry Lock Set",
    category: "hardware",
    subcategory: "door-locks",
    price: 76100,
    currency: "MXN",
    finishes: ["Aged Bronze", "Dark Bronze", "Silicon Bronze"],
    image: "/products/herrajes/chapas-cerrojos/product-1.jpg",
    artisanal: false,
    description: "Cerradura de entrada de bronce al silicio fundido a mano de Sun Valley Bronze — cada pieza individualmente fundida en arena y acabada a mano en Idaho.",
    descriptionEn: "Hand-cast silicon bronze entry lock set by Sun Valley Bronze. Each piece individually sand-cast and hand-finished in Idaho.",
    specifications: { "Material": "Silicon Bronze", "Backset": "2-3/8\" or 2-3/4\"", "Door Thickness": "1-3/4\" standard" },
  },
  {
    id: "54",
    sku: "SVB-ARCH-001",
    slug: "sun-valley-bronze-arch-entry",
    brand: "Sun Valley Bronze",
    name: "Cerradura Entrada Arch",
    nameEn: "Arch Entry Lock Set",
    category: "hardware",
    subcategory: "door-locks",
    price: 68500,
    currency: "MXN",
    finishes: ["Aged Bronze", "Dark Bronze", "Silicon Bronze", "Rust"],
    image: "/products/herrajes/chapas-cerrojos/product-1.jpg",
    artisanal: false,
    description: "Cerradura Arch de Sun Valley Bronze — forma de arco clásica en bronce al silicio fundido a mano.",
    descriptionEn: "Sun Valley Bronze Arch entry set — classic arch form in hand-cast silicon bronze.",
  },
  {
    id: "55",
    sku: "SVB-HAMPTON-001",
    slug: "sun-valley-bronze-hampton-entry",
    brand: "Sun Valley Bronze",
    name: "Cerradura Entrada Hampton",
    nameEn: "Hampton Entry Lock Set",
    category: "hardware",
    subcategory: "door-locks",
    price: 58700,
    currency: "MXN",
    finishes: ["Aged Bronze", "Dark Bronze", "Silicon Bronze"],
    image: "/products/herrajes/chapas-cerrojos/product-1.jpg",
    artisanal: false,
    description: "Cerradura Hampton de Sun Valley Bronze — diseño tradicional con textura martillada sutil.",
    descriptionEn: "Sun Valley Bronze Hampton entry set — traditional design with subtle hammered texture.",
  },
  {
    id: "56",
    sku: "SVB-MESA-001",
    slug: "sun-valley-bronze-mesa-entry",
    brand: "Sun Valley Bronze",
    name: "Cerradura Entrada Mesa",
    nameEn: "Mesa Entry Lock Set",
    category: "hardware",
    subcategory: "door-locks",
    price: 38700,
    currency: "MXN",
    finishes: ["Aged Bronze", "Silicon Bronze", "Rust"],
    image: "/products/herrajes/chapas-cerrojos/product-1.jpg",
    artisanal: false,
    description: "Cerradura Mesa de Sun Valley Bronze — líneas limpias del suroeste, perfil bajo, bronce al silicio.",
    descriptionEn: "Sun Valley Bronze Mesa entry set — clean Southwestern lines, low profile, silicon bronze.",
  },
  {
    id: "57",
    sku: "EMT-HAMPTON-001",
    slug: "emtek-hampton-knob",
    brand: "Emtek",
    name: "Perilla Hampton Edition",
    nameEn: "Hampton Edition Door Knob",
    category: "hardware",
    subcategory: "door-locks",
    price: 4003,
    currency: "MXN",
    finishes: ["Satin Nickel", "Oil Rubbed Bronze", "Polished Chrome", "Flat Black"],
    image: "/products/herrajes/chapas-cerrojos/product-1.jpg",
    artisanal: false,
    description: "Perilla Hampton Edition de Emtek — diseño clásico americano con construcción superior de latón sólido.",
    descriptionEn: "Emtek Hampton Edition door knob — classic American design with superior solid brass construction.",
  },
  // ─── HARDWARE: DEADBOLTS ───
  {
    id: "58",
    sku: "SVB-DEAD-001",
    slug: "sun-valley-bronze-deadbolt",
    brand: "Sun Valley Bronze",
    name: "Cerrojo de Bronce",
    nameEn: "Bronze Deadbolt",
    category: "hardware",
    subcategory: "deadbolts",
    price: 18500,
    currency: "MXN",
    finishes: ["Aged Bronze", "Dark Bronze", "Silicon Bronze"],
    image: "/products/herrajes/chapas-cerrojos/product-1.jpg",
    artisanal: false,
    description: "Cerrojo de bronce al silicio Sun Valley Bronze — combina con cualquier set de cerradura de la colección.",
    descriptionEn: "Sun Valley Bronze silicon bronze deadbolt — matches any lock set in the collection.",
  },
  {
    id: "59",
    sku: "EMT-DEAD-001",
    slug: "emtek-solid-brass-deadbolt",
    brand: "Emtek",
    name: "Cerrojo de Latón Sólido",
    nameEn: "Solid Brass Deadbolt",
    category: "hardware",
    subcategory: "deadbolts",
    price: 3800,
    currency: "MXN",
    finishes: ["Satin Nickel", "Oil Rubbed Bronze", "Polished Chrome", "Flat Black"],
    image: "/products/herrajes/chapas-cerrojos/product-1.jpg",
    artisanal: false,
    description: "Cerrojo de latón sólido Emtek — perfil bajo, mecanismo de cilindro seguro.",
    descriptionEn: "Emtek solid brass deadbolt — low profile, secure cylinder mechanism.",
  },
  // ─── HARDWARE: PULLS & HOOKS ───
  {
    id: "60",
    sku: "CC-KNOCKER-TRAD",
    slug: "traditional-bronze-door-knocker",
    brand: "Counter Cultures",
    name: "Aldaba Tradicional de Bronce",
    nameEn: "Traditional Bronze Door Knocker",
    category: "hardware",
    subcategory: "pulls-hooks",
    price: 1850,
    currency: "MXN",
    finishes: ["Natural Bronze", "Fine Black", "Faded Black"],
    image: "/products/herrajes/artesanales/product-1.jpg",
    artisanal: true,
    description: "Aldaba tradicional de bronce fundido a mano — diseño clásico para puertas de entrada.",
    descriptionEn: "Hand-cast traditional bronze door knocker — classic design for entry doors.",
  },
  {
    id: "61",
    sku: "CC-KNOCKER-LEON",
    slug: "leon-bronze-door-knocker",
    brand: "Counter Cultures",
    name: "Aldaba León de Bronce",
    nameEn: "León Bronze Door Knocker",
    category: "hardware",
    subcategory: "pulls-hooks",
    price: 2300,
    currency: "MXN",
    finishes: ["Natural Bronze", "Fine Black"],
    image: "/products/herrajes/artesanales/product-1.jpg",
    artisanal: true,
    description: "Aldaba león de bronce fundido a mano — pieza escultural para puertas de entrada.",
    descriptionEn: "Hand-cast león bronze door knocker — sculptural piece for entry doors.",
  },
  {
    id: "62",
    sku: "CC-HOOK-ARO",
    slug: "bronze-aro-hook",
    brand: "Counter Cultures",
    name: "Gancho Aro de Bronce",
    nameEn: "Bronze Aro Hook",
    category: "hardware",
    subcategory: "pulls-hooks",
    price: 450,
    currency: "MXN",
    finishes: ["Natural Bronze", "Fine Black", "Faded Black"],
    image: "/products/herrajes/artesanales/product-1.jpg",
    artisanal: true,
    description: "Gancho Aro de bronce fundido a mano — forma circular minimalista para abrigos y batas.",
    descriptionEn: "Hand-cast bronze Aro hook — minimalist circular form for coats and robes.",
  },
  {
    id: "63",
    sku: "CC-HOOK-HEX",
    slug: "bronze-hex-hook",
    brand: "Counter Cultures",
    name: "Gancho Hex de Bronce",
    nameEn: "Bronze Hex Hook",
    category: "hardware",
    subcategory: "pulls-hooks",
    price: 580,
    currency: "MXN",
    finishes: ["Natural Bronze", "Fine Black", "Faded Black"],
    image: "/products/herrajes/artesanales/product-1.jpg",
    artisanal: true,
    description: "Gancho Hex de bronce fundido a mano — forma hexagonal geométrica moderna.",
    descriptionEn: "Hand-cast bronze Hex hook — modern geometric hexagonal form.",
  },
  {
    id: "64",
    sku: "EMT-LAURENT-001",
    slug: "emtek-laurent-pull",
    brand: "Emtek",
    name: "Jaladera Laurent",
    nameEn: "Laurent Cabinet Pull",
    category: "hardware",
    subcategory: "pulls-hooks",
    price: 5068,
    currency: "MXN",
    finishes: ["Satin Nickel", "Oil Rubbed Bronze", "Polished Chrome", "Flat Black", "Satin Brass"],
    image: "/products/herrajes/chapas-cerrojos/product-1.jpg",
    artisanal: false,
    description: "Jaladera Laurent de Emtek — diseño contemporáneo con bordes biselados, latón sólido.",
    descriptionEn: "Emtek Laurent cabinet pull — contemporary design with beveled edges, solid brass.",
  },
] as const;
