export const SITE_CONFIG = {
  name: "Counter Cultures",
  tagline: "The Connected System",
  description:
    "San Miguel de Allende's premier bath and kitchen fixture destination. Where world-class design meets the soul of Mexican craft.",
  url: "https://countercultures.com.mx",
  showroom: {
    address: "Providencia, San Miguel de Allende, Guanajuato, Mexico",
    phone: "+52 415 XXX XXXX",
    email: "info@countercultures.com.mx",
    whatsapp: "+52 415 XXX XXXX",
    hours: "Lunes a Viernes, 10:00 – 18:00",
  },
  social: {
    instagram: "https://instagram.com/countercultures",
    facebook: "https://facebook.com/countercultures",
    pinterest: "https://pinterest.com/countercultures",
  },
} as const;

export const NAV_LINKS = [
  {
    label: { en: "Shop", es: "Tienda" },
    href: "/shop",
    children: [
      { label: { en: "Bathroom", es: "Baño" }, href: "/shop/bathroom" },
      { label: { en: "Kitchen", es: "Cocina" }, href: "/shop/kitchen" },
      { label: { en: "Door Hardware", es: "Chapas y Herrajes" }, href: "/shop/hardware" },
    ],
  },
  {
    label: { en: "Brands", es: "Marcas" },
    href: "/brands",
  },
  {
    label: { en: "Artisanal", es: "Artesanal" },
    href: "/artisanal",
  },
  {
    label: { en: "Our Story", es: "Nuestra Historia" },
    href: "/our-story",
  },
  {
    label: { en: "Insights", es: "Insights" },
    href: "/insights",
  },
  {
    label: { en: "Resources", es: "Recursos" },
    href: "/resources",
  },
] as const;

export const BRANDS = [
  { name: "Kohler", slug: "kohler" },
  { name: "TOTO", slug: "toto" },
  { name: "Brizo", slug: "brizo" },
  { name: "BLANCO", slug: "blanco" },
  { name: "California Faucets", slug: "california-faucets" },
  { name: "Sun Valley Bronze", slug: "sun-valley-bronze" },
  { name: "Emtek", slug: "emtek" },
  { name: "Badeloft", slug: "badeloft" },
  { name: "Banté", slug: "bante" },
  { name: "Mistoa", slug: "mistoa" },
  { name: "Villeroy & Boch", slug: "villeroy-boch" },
  { name: "AquaSpa", slug: "aquaspa" },
] as const;

export const PRODUCT_CATEGORIES = {
  bathroom: {
    label: { en: "Bathroom", es: "Baño" },
    slug: "bathroom",
    subcategories: [
      { slug: "sinks", label: { en: "Sinks & Basins", es: "Lavabos" } },
      { slug: "faucets", label: { en: "Faucets", es: "Grifos" } },
      { slug: "bathtubs", label: { en: "Bathtubs", es: "Bañeras" } },
      { slug: "tub-fillers", label: { en: "Tub Fillers", es: "Llenadores de Bañera" } },
      { slug: "toilets", label: { en: "Toilets", es: "Sanitarios" } },
      { slug: "showers", label: { en: "Showers", es: "Regaderas y Duchas" } },
      { slug: "accessories", label: { en: "Accessories", es: "Accesorios" } },
      { slug: "drains", label: { en: "Drains", es: "Drenajes" } },
    ],
  },
  kitchen: {
    label: { en: "Kitchen", es: "Cocina" },
    slug: "kitchen",
    subcategories: [
      { slug: "sinks", label: { en: "Sinks", es: "Tarjas y Fregaderos" } },
      { slug: "faucets", label: { en: "Faucets", es: "Mezcladoras" } },
      { slug: "appliances", label: { en: "Appliances", es: "Electrodomésticos" } },
      { slug: "range-hoods", label: { en: "Range Hoods", es: "Campanas" } },
    ],
  },
  hardware: {
    label: { en: "Door Hardware", es: "Chapas y Herrajes" },
    slug: "hardware",
    subcategories: [
      { slug: "entry-locks", label: { en: "Entry Lock Sets", es: "Chapas de Entrada" } },
      { slug: "interior-locks", label: { en: "Interior Lock Sets", es: "Chapas Interiores" } },
      { slug: "sliding-door", label: { en: "Sliding Door Hardware", es: "Puertas Corredizas" } },
      { slug: "pulls-hooks", label: { en: "Pulls & Hooks", es: "Jaladeras y Ganchos" } },
      { slug: "knobs", label: { en: "Door Knobs", es: "Perillas" } },
    ],
  },
} as const;

// Sample product data — will be replaced by Google Sheets API
export const SAMPLE_PRODUCTS = [
  {
    id: "1",
    sku: "MIST-SURCO-001",
    brand: "Mistoa",
    name: "Lavabo Surco",
    nameEn: "Surco Basin",
    category: "bathroom",
    subcategory: "sinks",
    price: 7500,
    currency: "MXN",
    finishes: ["Gris Natural", "Arcilla", "Rosa Crudo", "Durazno", "Mostaza", "Menta", "Azul Somero", "Azul Profundo", "Carbon", "Coco"],
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
    artisanal: true,
    description: "Handcrafted artisanal basin by Mistoa, available in 10 curated colorways inspired by the Mexican landscape.",
  },
  {
    id: "2",
    sku: "MIST-POAS-001",
    brand: "Mistoa",
    name: "Lavabo Poas",
    nameEn: "Poas Basin",
    category: "bathroom",
    subcategory: "sinks",
    price: 8900,
    currency: "MXN",
    finishes: ["Gris Natural", "Arcilla", "Rosa Crudo", "Durazno", "Mostaza", "Menta", "Azul Somero", "Azul Profundo", "Carbon", "Coco"],
    image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80",
    artisanal: true,
    description: "Organic form meets Mexican craft tradition. Each Poas basin is hand-shaped and finished by master artisans.",
  },
  {
    id: "3",
    sku: "TOTO-AIMES-001",
    brand: "TOTO",
    name: "Aimes® Lavabo Submontar",
    nameEn: "Aimes® Undermount Lavatory",
    category: "bathroom",
    subcategory: "sinks",
    price: 12316,
    currency: "MXN",
    finishes: ["Algodón", "Hueso", "Blanco Colonial", "Beige Sedona", "Ebony"],
    image: "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=600&q=80",
    artisanal: false,
    description: "TOTO's Aimes undermount lavatory combines refined geometry with CEFIONTECT ceramic glaze technology.",
  },
  {
    id: "4",
    sku: "CC-MICHELLE-001",
    brand: "Counter Cultures",
    name: "Michelle Vessel Cobre Brillado",
    nameEn: "Michelle Polished Copper Vessel",
    category: "bathroom",
    subcategory: "sinks",
    price: 5156,
    currency: "MXN",
    finishes: ["Cobre Brillado"],
    image: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=600&q=80",
    artisanal: true,
    description: "Hand-hammered polished copper vessel sink, designed by Roger Williams and crafted by Mexican coppersmiths.",
  },
  {
    id: "5",
    sku: "BLN-IKON-30",
    brand: "BLANCO",
    name: "Ikon Silgranit Con Mandil 30\"",
    nameEn: "Ikon 30\" Silgranit Apron Sink",
    category: "kitchen",
    subcategory: "sinks",
    price: 39341,
    currency: "MXN",
    finishes: ["Anthracite", "Blanco", "Cinder", "Truffle", "Gris Metálico", "Café", "Gris Volcánico", "Coal Negro"],
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
    artisanal: false,
    description: "BLANCO's iconic apron front sink in patented Silgranit material — heat, scratch, and stain resistant.",
  },
  {
    id: "6",
    sku: "KOH-STRIVE-24",
    brand: "Kohler",
    name: "Strive Fregadero 24\"",
    nameEn: "Strive 24\" Undermount Kitchen Sink",
    category: "kitchen",
    subcategory: "sinks",
    price: 17726,
    currency: "MXN",
    finishes: ["Stainless Steel"],
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
    artisanal: false,
    description: "Kohler's Strive undermount single-basin kitchen sink — tight radius corners, SilentShield technology.",
  },
  {
    id: "7",
    sku: "SVB-ENTRY-CONT",
    brand: "Sun Valley Bronze",
    name: "Cerradura Entrada Contemporary",
    nameEn: "Contemporary Entry Lock Set",
    category: "hardware",
    subcategory: "entry-locks",
    price: 76100,
    currency: "MXN",
    finishes: ["Aged Bronze", "Dark Bronze", "Silicon Bronze"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80",
    artisanal: false,
    description: "Hand-cast silicon bronze entry lock set by Sun Valley Bronze. Each piece individually sand-cast and hand-finished in Idaho.",
  },
  {
    id: "8",
    sku: "EMT-HAMPTON-001",
    brand: "Emtek",
    name: "Perilla Hampton Edition",
    nameEn: "Hampton Edition Door Knob",
    category: "hardware",
    subcategory: "knobs",
    price: 4003,
    currency: "MXN",
    finishes: ["Satin Nickel", "Oil Rubbed Bronze", "Polished Chrome", "Flat Black"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80",
    artisanal: false,
    description: "Emtek's Hampton Edition knob — classic American design with superior solid brass construction.",
  },
  {
    id: "9",
    sku: "BRIZO-LITZE-001",
    brand: "Brizo",
    name: "Litze Mezcladora Extraíble",
    nameEn: "Litze Pull-Down Kitchen Faucet",
    category: "kitchen",
    subcategory: "faucets",
    price: 28500,
    currency: "MXN",
    finishes: ["Chrome", "Matte Black", "Polished Nickel", "Luxe Gold"],
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80",
    artisanal: false,
    description: "The Brizo Litze collection brings industrial precision to the kitchen — exposed springs, articulating joints, and a bridge design that turns your sink into a statement.",
  },
  {
    id: "10",
    sku: "BDL-FREE-001",
    brand: "Badeloft",
    name: "Bañera Independiente",
    nameEn: "Freestanding Bathtub",
    category: "bathroom",
    subcategory: "bathtubs",
    price: 45000,
    currency: "MXN",
    finishes: ["Glossy White", "Matte White"],
    image: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80",
    artisanal: false,
    description: "Badeloft freestanding soaking tub — seamless mineral casting, ergonomic form, easy-clean surface.",
  },
  {
    id: "11",
    sku: "CF-BRIDGE-001",
    brand: "California Faucets",
    name: "Mezcladora Puente Estilo Clásico",
    nameEn: "Bridge-Style Kitchen Faucet",
    category: "kitchen",
    subcategory: "faucets",
    price: 22000,
    currency: "MXN",
    finishes: ["Polished Chrome", "Satin Nickel", "Antique Brass", "Oil Rubbed Bronze", "Matte Black"],
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80",
    artisanal: false,
    description: "California Faucets bridge-style kitchen faucet — handcrafted in Huntington Beach, CA with over 30 finish options.",
  },
  {
    id: "12",
    sku: "CC-ELOY-001",
    brand: "Counter Cultures",
    name: "Eloy Lavabo de Cobre",
    nameEn: "Eloy Copper Basin",
    category: "bathroom",
    subcategory: "sinks",
    price: 8923,
    currency: "MXN",
    finishes: ["Hammered Copper", "Cobre Oscuro"],
    image: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=600&q=80",
    artisanal: true,
    description: "Rectangular hammered copper basin, hand-forged by Mexican artisans. Each piece carries the unique marks of its maker.",
  },
] as const;
